name: Node.js Package

on:
  release:
    types:
      - published

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: npm install yarn -g
      - run: yarn
      - run: npm publish ./dist --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
